apiVersion: v1
kind: Service
metadata:
  name: my-java-app-service
spec:
  selector:
    app: my-java-app
  ports:
    - protocol: TCP
      port: 80 # Port for external access
      targetPort: 8080 # Port of the application inside the container
  type: LoadBalancer # Or ClusterIP for internal access
